name: Build and Publish Docker on Push

on:
  push:
    branches:
      - master

jobs:
  build_and_push:
    strategy:
      fail-fast: false
      matrix:
        platform:
          - linux/amd64
          - linux/arm64
        include:
          - platform: linux/amd64
            runner: ubuntu-latest
          - platform: linux/arm64
            runner: ubuntu-24.04-arm
    runs-on: ${{ matrix.runner }}
    env:
      IMAGE_NAME: rizumu-bot
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: write imageenv file
        shell: bash
        run: |
          cat << EOS > imageenv.json
          {
            "commitId": "${{github.sha}}",
            "ref": "${{github.ref}}",
            "imageName": "${{ env.IMAGE_NAME }}",
            "trigger": "master"
          }
      #          echo -e "COMMIT_ID=${{ github.sha }}\n" > .imageenv
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=sha,format=sha,prefix=
            type=sha,format=short,prefix=
          flavor: latest

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: ${{ matrix.platform }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
